baseurl = "https://lek-nrw.de"
title = "LEK NRW"
# theme = "hugo-theme-cleanwhite"
theme = "lek-nrw-theme"
languageCode = "de-de"
preserveTaxonomyNames = true
hasCJKLanguage = false

[services]
  # Enable comments by entering your Disqus shortname
  [services.disqus]
    shortname = ""
  [services.googleAnalytics]
    id = ""

[pagination]
  pagerSize = 5 # frontpage pagination

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  # Kategorien verstecken!
  hideCategories = true
  # Logo anstatt Title im Schriftzug
  logo = "img/logo-lek-nrw.png"      # Pfad relativ zu /static
  showLogoOnHero = true

  header_image = "img/home-bg-lek-hero.png"
  SEOTitle = "LEK - Landeselternkonferenz NRW - Der Dachverband der Kreis und Stadtschulpflegschaften in NRW"
  description = "LEK - Landeselternkonferenz NRW - Der Dachverband der Kreis und Stadtschulpflegschaften in NRW"
  keyword = "LEK, Landeselternkonferenz, Landeselternkonferenz NRW, LEK NRW, Dachverband, Kreisschulpflegschaft, Stadtschulpflegschaft, Stadtschulpflegschaften NRW, Kreisschulpflegschaft NRW, Schulpflegschaft"
  slogan = "Der Dachverband der Kreis und Stadtschulpflegschaften in NRW"
  upstreamAttribution = true

  image_404 = "img/404-bg.jpg"
  title_404 = "Das war wohl nichts... 404"
  omit_categories = false

  # leancloud storage for page view counter
  page_view_counter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = false
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Landeselternkonferenz NRW - Der Dachverband der Kreis und Stadtschulpflegschaften in NRW"
  #sidebar_avatar = "img/avatar-zhaohuabing.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_avatar = "img/logo-lek-nrw.png"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 1 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  # Twikoo comments
  # Follow https://twikoo.js.org/ to set up your own env_id
  twikoo_env_id = ""

  # Artalk comments
  # Follow https://artalk.js.org/ to set up your own server
  artalk_enable = true
  artalk_server = "https://xxx.xxx.com"
  artalk_site = "xxx blog"

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = false 
  # reward_guide = "如果这篇文章对你有用,请随意打赏" 

  friends = false
  bookmarks = false
  about_me = true

  # Last posts
  last_posts = true
  #last_posts_title = "LAST POSTS"
  #last_posts_count = 5

  # Include any custom CSS and/or JS files, url or relative to /static folder
  #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  custom_css = ["css/custom.css"]

  [params.social]
  rss            = true 
  email          = "youremail@gmail.com"
  facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  twitter       = "full profile url in twitter"
  #linkedin       = "https://www.linkedin.com/in/yourlinkedinid"
  #stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
  instagram     = "full profile url in instagram"
  github         = "https://github.com/yourgithub"
  #wechat         = "your wechat qr code image"
  #medium        = "full profile url in medium"
  #slack         = "full workspace url in slack"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  #gitlab        = "full profile url in gitlab"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #xing          = "https://www.xing.com/profile/yourxingid"
  #git           = "full profile url for git user"
  
  [[params.friend_link]]
  title = "Landtag NRW"
  shref =  "https://landtag.nrw.de"

  [[params.bookmark_link]]
  title =  "Martin Fowler"
  href =  "https://martinfowler.com"
  [[params.bookmark_link]]
  title = "ServiceMesher"
  href =  "http://www.servicemesher.com"
  [[params.bookmark_link]]
  title =  "Pxhere"
  href = "https://pxhere.com"
  [[params.bookmark_link]]
  title = "unsplash"
  href = "https://unsplash.com"
  

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[mediaTypes]
  [mediaTypes.'font/woff']
    suffixes = ['woff']
  [mediaTypes.'font/woff2']
    suffixes = ['woff2']

[menu]
  [[menu.main]]
    name = "Über uns"
    url = "/ueber-uns"
    weight = 1
  [[menu.main]]
    name = "Vorstand"
    url = "/ueber-uns/vorstand"
    parent = "Über uns"
    weight = 1   
  [[menu.main]]
    name = "Arbeitsgruppen"
    url = "/ueber-uns/arbeitsgruppen"
    parent = "Über uns"
    weight = 1      
  [[menu.main]]
    name = "Mitglieder"
    url = "/ueber-uns/mitglieder"
    parent = "Über uns"
    weight = 1        
  [[menu.main]]
    name = "Termine"
    url = "/termine/"
    identifier = "termine"
    weight = 2
  [[menu.main]]
    name = "Veröffentlichung"
    url = "/veroeffentlichung/"
    identifier = "Veröffentlichung"
    weight = 2
  [[menu.main]]
    name = "Stellungsnahme"
    url = "/veroeffentlichung/stellungsnahme/"
    parent = "Veröffentlichung"
    weight = 1
  [[menu.main]]
    name = "Pressemeldung"
    url = "/veroeffentlichung/pressemeldung/"
    parent = "Veröffentlichung"
    weight = 2  
  # Hauptmenüpunkt
  [[menu.main]]
  name = "ABOUT"
  url = "/about/"
  identifier = "about"
  weight = 30

  # Submenüs
  [[menu.main]]
  name = "Team"
  url = "/about/team/"
  parent = "about"
  weight = 31

  [[menu.main]]
  name = "Kontakt"
  url = "/about/kontakt/"
  parent = "about"
  weight = 32
  
  [[menu.main]]
  name = "Links"
  url = "/links"
  weight = 50